name: Deploy Clip Request

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: get repository name
        run: echo "subdirectory=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            repository: 'Turger/ClipRequestReward'
            github-server-url: 'https://gitlab.com'
            ref: 'refs/heads/main'
            token: ${{ secrets.GITLAB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 'lts/*'
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: cliprequestreward-deployment
          path: ./dist

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: cliprequestreward-deployment
